# SETUP
baseurl = "https://sredevops.dev" # the base hostname & protocol for your site, e.g. https://sredevops.dev
DefaultContentLanguage = "es"
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm"] # disable hugo's content that we don't need...

title = "SREDevOps.dev" # page title -> see ./layouts/partials/head.html

googleAnalytics = "" # if needed...

[author]
    name = "Nicolás Georger"
    email = "info@sredevops.cl"

[params]
    description = "Desc." # page description -> see ./layouts/partials/head.html
    images = [] #add images here as "img/name.ext" (points to s./static/img/) to populate the default og and twitter <meta> attributes -> see ./layouts/partials/head.html

# these items will be rendered 1. into a tooltip in the navbar and 2. into the footer - consider that there's limited space when adding more items -> see ./layouts/partials
[[params.social]]
    title = "Twitter"
    url = "https://twitter.com/#" # add your twitter handle
[[params.social]]
    title = "LinkedIn"
    url = "https://linkedin.com/company/#" # add your linkedin profile URL
[[params.social]]
    title = "GitHub"
    url = "https://GitHub.com/sredevopsdev"

